baseURL = 'https://tiamkere.github.io/'
languageCode = 'en-us'
title = "Tiam's Blog"
theme = 'nostyleplease'

[[module.mounts]]
source = 'static'
target = 'static'

[[module.mounts]]
source = 'images'
target = 'static/images'